version: '3.8'

services:

  # krakend:
  #   container_name: ch_krakend
  #   build: . 
  #   restart: always
  #   ports:
  #     - "8191:8090"

  postgres:
    # build: 
    #   dockerfile: ./postgres/Dockerfile
    image: postgres:14
    restart: always
    container_name: lct_postgres_db
    environment:
      POSTGRES_USER: lct_guest
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lct_postgres_db
    ports:
      - '9559:5432'
    volumes:
      - ./postgres/container_data/db:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: shureck
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  minio:
    container_name: ch_minio_storage
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_PORT=9000
      - MINIO_ROOT_USER=rtuitlab
      - MINIO_ROOT_PASSWORD=RedAlert
      - MINIO_BASE_STORAGE=ch-main-storage
      - MINIO_PROXY_HOST=minio

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5677:5672"   # AMQP порт
      - "15677:15672" # HTTP порт для веб-интерфейса
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rtuitlab
      RABBITMQ_DEFAULT_PASS: qweqweqwe

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6377:6379"
    volumes:
      - ./redis-data:/data

volumes:
  pgadmin: